add new command news things 3

diff --git a/scautofire b/scautofire
--- a/scautofire
+++ b/scautofire
@@ -24,7 +24,7 @@ hash5=$(hash_gen)
 
 create_keepNote(){
 # create directory
-dir=$2/$1
+dir=$1
 mkdir $dir
 #create node 
 cat <<EOF > $dir/node.xml
@@ -329,12 +329,15 @@ EOF
 
 verify_cidr_param(){
 if expr "$1" : '.*:.*' >/dev/null; then
-   if [ "$(echo "$1" | cut -d: -f2)" != "" ]; then
+   box="$(echo "$1" | cut -d: -f2)"
+   if [ "$box" != "" ]; then
      verify_ip $(echo "$1" | cut -d: -f1)
      if [ $? -eq 0 ]; then
         echo "${RED}ERROR: parameter \"--cidr=$1\" is not correct. Ip part is wrong. \n${YELLOW}Right format: ip:MachineName${NC}\n"
         exit 2
      else
+      box_name="$box"
+      cidrip="$(echo "$1" | cut -d: -f1)"
       return 0
      fi
    else
@@ -536,7 +539,11 @@ while [ "$1" != "" ]; do
             ;;    
         --path)
             if [ -d "$VALUE" ]; then
-              rootDir=$VALUE
+              if expr "$VALUE" : '/.*/$' >/dev/null || [ ${#VALUE} = 1 ]; then
+                 rootDir=$VALUE
+              else
+                 rootDir="$VALUE/"
+              fi   
               required=$((required+1))
             else
               echo "${RED}ERROR: the path \"$VALUE\" is not a directory !!${NC}\n"
@@ -593,45 +600,66 @@ elif [ "$masscan" = "on" ] && [ "$interface" = "" ]; then
        echo "${RED}ERROR: the parameter '--interface' must be set when '--masscan' is enabled${NC}\n"
        usage $cmd
        exit 1
+elif [ "$cmd" = "addto" ] && [ "$name" != "" ]; then
+       echo "${RED}ERROR: do not use the  parameter '--name' with the 'addto' command${NC}\n"
+       usage $cmd
+       exit 1     
 fi
 # verify --cidr and --interface
+box_name=""
 if [ ! -z $cidrip ]; then 
   verify_cidr_param $cidrip
 fi
 if [ "$masscan" = "on" ]; then  
   verify_net_interface $interface
 fi
+
 #Verify if script run as root
 if [ $(id -u)  -ne 0 ]; then 
         echo "${YELLOW}This script must be run as root, use sudo "$0" instead\n" 1>&2
         exit 1
 fi
-exit 1
-    #*******************
-dir=$rootDir/$name
-scanfile=$dir/scan.txt
-ipfile=$dir/boxes_ips.txt
-#****************************
-create_keepNote $name $rootDir && \
-cp -r $KEEPSCAN/template/__NOTEBOOK__ $dir/ &&\
 
+if [ "$cmd" = "new" ]; then
+   dir="$rootDir$name"
+   scanfile=$dir/scan.txt
+   ipfile=$dir/boxes_ips.txt
+elif [ -f "${rootDir}node.xml" ]; then  
+    dir="$rootDir"
+    scanfile="${dir}scan.txt"
+    ipfile="${dir}boxes_ips.txt"
+else
+    echo "${RED}ERROR: parameter '--path', the directory '$rootDir' is not a valid keepnote report${NC}\n"
+        exit 1
+fi   
+num_ips=0
+echo $cidrip
+echo $box_name
+exit 1
+if [ "$cmd" = "new" ]; then
+   create_keepNote $dir && \
+   cp -r $KEEPSCAN/template/__NOTEBOOK__ $dir/ 
+fi
 if [ "$file_ips" != "" ]; then
    cat $file_ips > $ipfile
+fi
+if [ "$box_name" != "" ]; then
+   num_ips=$((num_ips+1))
+   create_sub_kpn $cidrip $dir $scantype $masscan $interface $rate $router_ip
 else
    nmap --top-ports 100 -oN $scanfile $cidrip 
    cat $scanfile |  grep -i "Nmap scan" | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' > $ipfile 
-fi
-num_ips=0
-for ip in $(cat $ipfile );do
-    verify_ip $ip
-    if [ $? -ne 0 ]; then
-       num_ips=$((num_ips+1))
-       create_sub_kpn $ip $dir $scantype $masscan $interface $rate $router_ip
-    else
+
+   for ip in $(cat $ipfile );do
+     verify_ip $ip
+     if [ $? -ne 0 ]; then
+        num_ips=$((num_ips+1))
+        create_sub_kpn $ip $dir $scantype $masscan $interface $rate $router_ip
+     else
        echo "${RED}\"$ip\" is not a valid ip${NC}"
-    fi 
-done 
-   
+     fi 
+   done 
+fi   
 if [ $num_ips -gt 0 ]; then   
    echo "${GREEN} $0 successfully scaned $num_ips ip(s)"
    # If user want to let created report writable by a local user 
