add symlink for masscan, and chanfe scautofire code, create a single install.sh

diff --git a/scautofire b/scautofire
--- a/scautofire
+++ b/scautofire
@@ -1,6 +1,25 @@
 #!/bin/zsh
-# create the keepNote directory functions
+# color define
+RED='\033[0;31m'
+YELLOW='\033[0;33m'
+GREEN='\033[0;32m'
+NC='\033[0m'
 
+# activate scautofire python venv
+if [ -d /usr/share/KeepScan ]
+  then
+    VENV="/usr/share/KeepScan/.env/"
+  elif [ -d "$PWD/.env" ]
+   then
+    VENV="$PWD/.env"
+  else
+    echo "${RED}\n[ERROR]: scautofire python venv not found, try to reinstall the project.${NC}"
+    exit 2
+fi
+
+source "$VENV/bin/activate"
+
+# create the keepNote directory functions
 hash_gen(){
   id=""
   for i in 8 4 4 4 12
@@ -15,6 +34,7 @@ hash_gen(){
    done
  echo $id
 }
+
 # hashes used for templates
 hash1=$(hash_gen)
 hash2=$(hash_gen)
@@ -904,17 +924,11 @@ fi
 }
 
 verify_net_interface(){
-if [ "$(ip -br addr | grep tun0 | cut -d" " -f 1)" != "$1" ]; then
+if [ "$(ip -br addr | grep $1 | cut -d" " -f 1)" != "$1" ]; then
    echo "${RED}\n[ERROR]: parameter \"--interface=$1\" is not correct. Interface '$1' not found ${NC}\n" 
    exit 2
 fi   
 }
-
-# color define
-RED='\033[0;31m'
-YELLOW='\033[0;33m'
-GREEN='\033[0;32m'
-NC='\033[0m'
 
 usage()
 {
@@ -1278,8 +1292,11 @@ if [ $num_ips -gt 0 ]; then
    fi 
    # if script runs with sudo, run the keepnote as the sudo user
    if [ "$SUDO_USER" != "" ]; then
-     #chown -R ${SUDO_USER}:${SUDO_USER} $dir 
-     chown -R ${SUDO_USER} $dir 
+     if [ $(getent group "${SUDO_USER}") ]; then
+       chown -R ${SUDO_USER}:${SUDO_USER} $dir
+     else
+       chown -R ${SUDO_USER} $dir 
+     fi
      if [ -f "${dir}notebook.nbk"  ]; then
        su -c "keepnote --no-show-errors --no-default  $dir &" $SUDO_USER && \
        exit 0
